// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwXOaUgnquJYPOvP0CzvwjXqgpInDI53o',
    appId: '1:1077910428362:web:d18b7d27da977bc3993233',
    messagingSenderId: '1077910428362',
    projectId: 'project-78828',
    authDomain: 'project-78828.firebaseapp.com',
    storageBucket: 'project-78828.firebasestorage.app',
    measurementId: 'G-JW6C9KWXQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjt9pjgfFe_NVokTTomSYc6OZWd1z7Ey8',
    appId: '1:1077910428362:android:b0466669c55f7861993233',
    messagingSenderId: '1077910428362',
    projectId: 'project-78828',
    storageBucket: 'project-78828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClenLcb4AU4vRvHqRIR-7VgQQuEgpTcew',
    appId: '1:1077910428362:ios:96b6534203ebc5b3993233',
    messagingSenderId: '1077910428362',
    projectId: 'project-78828',
    storageBucket: 'project-78828.firebasestorage.app',
    iosBundleId: 'com.example.profiletask.profileTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClenLcb4AU4vRvHqRIR-7VgQQuEgpTcew',
    appId: '1:1077910428362:ios:96b6534203ebc5b3993233',
    messagingSenderId: '1077910428362',
    projectId: 'project-78828',
    storageBucket: 'project-78828.firebasestorage.app',
    iosBundleId: 'com.example.profiletask.profileTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwXOaUgnquJYPOvP0CzvwjXqgpInDI53o',
    appId: '1:1077910428362:web:c61a953cd5ba8493993233',
    messagingSenderId: '1077910428362',
    projectId: 'project-78828',
    authDomain: 'project-78828.firebaseapp.com',
    storageBucket: 'project-78828.firebasestorage.app',
    measurementId: 'G-92NQ9D7K6B',
  );

}